### ISSUE TITLE
Window Maker does not respect GNUstep themes

### ISSUE THREAD

**Issue by probonopd** [window-maker/wmaker#4]
Window Maker does not respect GNUstep themes such as Rik.
At this point, I'd consider this to be a bug. At least if Window Maker is meant to be used in conjunction with GNUstep.

**Comment by gryf** [comment]
Do you have steps to reproduce that bug?

**Comment by probonopd** [comment]
To be precise, WPrefs.app does not follow the system theme (Rik in my case). Is it supposed to?
Thanks @gryf

**Comment by d-torrance** [comment]
No, WPrefs is a WINGs app, not a GNUstep one.  Currently, there is no such thing as a WINGs theme.

**Comment by probonopd** [comment]
Thanks @d-torrance. Forgive my ignorant question, but isn't Window Maker meant to be used in conjunction with GNUstep? Why are there two different systems for theming that are incompatible with each other?

**Comment by d-torrance** [comment]
GNUstep and Window Maker are distinct projects that happen to be used together frequently because they both continue the legacy of NeXSTEP.   See http://www.gnustep.org/information/wm.html.

WINGs, which is Window Maker's widget library and is used for WPrefs and the various Window Maker dialog boxes, is actually a recursive acronym meaning "**W**INGs **I**s **N**ot **G**NU**s**tep".  It currently has *no* theming capability.  The appearances of all the widgets are hard-coded in the source.

Personally, I think it would be really cool to improve WINGs so that it did support themes, and maybe even GNUstep themes.  I've played around with the code a bit, but it would be a big project.

**Comment by probonopd** [comment]
Thanks for the clarification @d-torrance.
